projects/legacy_system/legacy/apps/deliveries/urls.py
from django.urls import path

from apps.deliveries.views import (
    DeliveriesCreateView,
    DeliveriesDetailView,
    DeliveriesListView,
    DeliveriesUpdateView,
)

urlpatterns = [
    path("", DeliveriesListView.as_view(), name="list"),
    path("create/", DeliveriesCreateView.as_view(), name="create"),
    path("<uuid:pk>/editar", DeliveriesUpdateView.as_view(), name="update"),
    path("<uuid:pk>/detalhes", DeliveriesDetailView.as_view(), name="detail"),
]

projects/legacy_system/legacy/legacy/urls.py
from apps.deliveries.views import CustomLoginView, DashboardView, PartnerRouteListView
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", CustomLoginView.as_view()),
    path("logout/", LogoutView.as_view()),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("deliveries/", include(("apps.deliveries.urls", "apps.deliveries"), namespace="deliveries")),
    path(
        "partner-routes/",
        include(("apps.deliveries.partner_routes_urls", "apps.deliveries"), namespace="partner_routes"),
    ),
]

projects/legacy_system/legacy/apps/deliveries/models.py
import uuid

from django.db import models
from model_utils.models import TimeStampedModel


class PartnerStatusChoices(models.TextChoices):
    ACTIVE = "ACTIVE", "ACTIVE"
    INACTIVE = "INACTIVE", "INACTIVE"


class Partner(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField("name", max_length=100)
    status = models.CharField(
        "status",
        max_length=8,
        choices=PartnerStatusChoices.choices,
        default=PartnerStatusChoices.ACTIVE,
    )

    class Meta:
        verbose_name = "Patner"
        verbose_name_plural = "Patners"


class RouteStatusChoices(models.TextChoices):
    ACTIVE = "ACTIVE", "ACTIVE"
    INACTIVE = "INACTIVE", "INACTIVE"


class PartnerRoute(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    start_place = models.CharField("start_place", max_length=50)
    finish_place = models.CharField("finish_place", max_length=50)
    price = models.DecimalField("price", max_digits=5, decimal_places=2)
    partner = models.ForeignKey(Partner, on_delete=models.DO_NOTHING)
    status = models.CharField(
        "status",
        max_length=10,
        choices=RouteStatusChoices.choices,
        default=RouteStatusChoices.ACTIVE,
    )

    class Meta:
        verbose_name = "PartnerRoute"
        verbose_name_plural = "PartnerRoutes"
        unique_together = [["start_place", "finish_place", "partner_id"]]


class DeliveryStatusChoices(models.TextChoices):
    QUOTATION = "QUOTATION", "QUOTATION"
    IN_TRANSIT = "IN_TRANSIT", "IN_TRANSIT"
    DONE = "DONE", "DONE"


class DeliveryTypeChoices(models.TextChoices):
    QUOTATION = "QUOTATION", "QUOTATION"
    DELIVERY = "DELIVERY", "DELIVERY"


class Delivery(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sender_name = models.CharField("sender_name", max_length=100)
    sender_address = models.CharField("sender_address", max_length=100)
    sender_city = models.CharField("sender_city", max_length=50)
    sender_postal_code = models.CharField("sender_postal_code", max_length=10)

    receiver_name = models.CharField("receiver_name", max_length=100)
    receiver_address = models.CharField("receiver_address", max_length=100)
    receiver_city = models.CharField("receiver_city", max_length=50)
    receiver_postal_code = models.CharField("receiver_postal_code", max_length=10)

    freight_price = models.DecimalField("freight_price", max_digits=5, decimal_places=2, null=True)

    expected_delivery_date = models.DateField("expected_delivery_date", auto_now=False, auto_now_add=False)
    delivery_date = models.DateField("delivery_date", auto_now=False, auto_now_add=False, null=True)

    type = models.CharField(
        "type", max_length=9, choices=DeliveryTypeChoices.choices, default=DeliveryTypeChoices.QUOTATION
    )

    status = models.CharField(
        "status",
        max_length=10,
        choices=DeliveryStatusChoices.choices,
        default=DeliveryStatusChoices.QUOTATION,
    )
    partner_route = models.ForeignKey(PartnerRoute, on_delete=models.DO_NOTHING, null=True)

    class Meta:
        verbose_name = "Delivery"
        verbose_name_plural = "Deliveries"

projects/legacy_system/legacy/apps/deliveries/forms.py
from django.forms import DateField, DateInput, ModelForm

from .models import Delivery


class DeliveryForm(ModelForm):
    expected_delivery_date = DateField(widget=DateInput(attrs={"type": "date"}))

    class Meta:
        model = Delivery
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(DeliveryForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
        self.fields["freight_price"].required = False
        self.fields["delivery_date"].required = False
        self.fields["partner_route"].required = False


class DeliveryUpdateForm(ModelForm):
    expected_delivery_date = DateField(widget=DateInput(attrs={"type": "date"}))

    class Meta:
        model = Delivery
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        editable_fields = kwargs.pop("editable_fields", [])

        super(DeliveryUpdateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

        self.fields["freight_price"].required = False
        self.fields["delivery_date"].required = False
        self.fields["partner_route"].required = False

        for key, field in self.fields.items():
            if key not in editable_fields:
                field.disabled = True

projects/legacy_system/legacy/apps/deliveries/views.py
import requests
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from django.views.generic.base import TemplateView
from prettyconf import config

from tests.factories import DeliveryFactory

from .forms import DeliveryForm, DeliveryUpdateForm
from .models import Delivery, PartnerRoute


class CustomLoginView(LoginView):
    template_name = "site/login.html"
    extra_context = {"next": "www.google.com.br"}


class DashboardView(TemplateView):
    template_name = "site/dashboard.html"


class DeliveriesListView(ListView):
    paginate_by = 30
    model = Delivery


class DeliveriesCreateView(CreateView):
    form_class = DeliveryForm
    template_name = "deliveries/delivery_form.html"

    success_url = reverse_lazy("deliveries:list")

    def get_initial(self):
        delivery = DeliveryFactory.build()
        return delivery.__dict__

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"show_save_button": True})
        return context


class DeliveriesUpdateView(UpdateView):
    model = Delivery
    form_class = DeliveryUpdateForm
    template_name = "deliveries/delivery_form.html"

    success_url = reverse_lazy("deliveries:list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"editable_fields": ["status"]})

        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"show_save_button": True})
        return context


class DeliveriesDetailView(UpdateView):
    model = Delivery
    form_class = DeliveryUpdateForm
    template_name = "deliveries/delivery_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        url = f"{config('DELIVERIES_API')}/deliveries/{self.object.id}"
        delivery = requests.get(url, headers={"Authorization": config("API_TOKEN")}).json() or {}

        context.update({"show_save_button": False, "zpl": (delivery.get("zpl") or {}).get("url")})
        return context


class PartnerRouteListView(ListView):
    template_name = "partner_routes/list.html"
    paginate_by = 30
    model = PartnerRoute

    def get_queryset(self):
        queryset = super().get_queryset()

        if qPartner := self.request.GET.get("qPartner"):
            queryset = queryset.filter(partner=qPartner)
        if qSender := self.request.GET.get("qSender"):
            queryset = queryset.filter(start_place=qSender)
        if qReceiver := self.request.GET.get("qReceiver"):
            queryset = queryset.filter(finish_place=qReceiver)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(PartnerRouteListView, self).get_context_data(**kwargs)
        context["qPartner"] = self.request.GET.get("qPartner", "").strip()
        context["qSender"] = self.request.GET.get("qSender", "").strip()
        context["qReceiver"] = self.request.GET.get("qReceiver", "").strip()
        return context

projects/legacy_system/legacy/apps/deliveries/templates/partner_routes/list.html
<!doctype html>
<html lang="en">
{% include "site/_head.html" %}

<body>

    {% include "site/_header.html" %}

    <div class="container-fluid">
        <div class="row">
            {% include "site/_sidebarmenu.html" %}

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div
                    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Rotas de parceiro</h1>
                    <div class="btn-toolbar mb-2 mb-md-0">
                    
                        <div class="btn-group me-2">
                            <form method="get" action="{% url 'partner_routes:list' %}">
                                <div class="input-group mx-3">
                                    <input type="text" name="qPartner" value="{{qPartner}}" placeholder="Parceiro" class="form-control me-1"/>
                                    <input type="text" name="qSender" value="{{qSender}}" placeholder="Remetente" class="form-control me-1"/>
                                    <input type="text" name="qReceiver" value="{{qReceiver}}" placeholder="Destinatário" class="form-control me-1"/>
                                    <button type="submit" class="btn btn-sm btn-outline-info">Pesquisar</button>
                                </div>
                                
                            </form>
                        </div>

                    </div><div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group me-2">
                            <a type="button" href="{% url 'deliveries:create' %}" class="btn btn-sm btn-outline-secondary">Cadastrar
                                Entrega</a>
                        </div>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Parceiro</th>
                                <th scope="col">Remetente</th>
                                <th scope="col">Destinatário</th>
                                <th scope="col">Preço</th>
                            </tr>
                        </thead>
                        
                        <tbody>
                            {% for partner_route in object_list %}
                            <tr>
                                <td>{{partner_route.partner.name}} - {{partner_route.partner.id}}</td>
                                <td>{{partner_route.start_place}}</td>
                                <td>{{partner_route.finish_place}}</td>
                                <td>{{partner_route.price}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            
                            {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1">&laquo; Primeira</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                            {% endif %}
                            <span class="current">
                                
                                <li class="page-item disabled">
                                    <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>
                                </li>
                            </span>
                            {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li>
                            {% endif %}
                            
                        </ul>
                    </nav>
                </div>
            </main>
        </div>
    </div>
    {% include "site/_js.html" %}
</body>

</html>